name: Flutter Web CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"

      - name: Disable Flutter analytics
        run: flutter config --no-analytics
        working-directory: chatly

      - name: Install dependencies
        run: flutter pub get
        working-directory: chatly

      - name: Run tests
        run: flutter test
        working-directory: chatly
